title: Find a file in a tree
description: Finds a file in a given tree, either by path or matching a RegEx
options:
  - title: Path or RegEx
    property: path
    description: The path or RegEx of the file you want to find
    type: string
  - title: Tree
    property: tree
    description: A Git tree
    type: array
  - title: Multiple
    property: multiple
    description: Return an array of values instead of just the first one that matches
    default: false
examples:
  - type: findInTree
    path: example.md
  - type: findInTree
    path: /^_posts\// # Any file in the _posts folder
  - type: findInTree
    multiple: true
    path: /^_posts\// # All files in the _posts folder

    
