title: Remove branch protection
description: Removes the branch protection on a branch in the course repository
options:
  - title: Branch
    property: branch
    description: The branch name to remove branch protection
    default: '`master`'
    type: string
examples:
  - type: removeBranchProtection
  - type: removeBranchProtection
    branch: my-protected-branch