title: Octokit
description: Calls a method in the Octokit library
usage: Using the `method` option with a value like `issues.create`, use the Octokit library's entire list of available methods. You can see what those are [on the Octokit docs](https://octokit.github.io/rest.js)
options:
  - title: Octokit method
    property: method
    description: Object dot notation for the Octokit method
    required: true
    type: string
  - title: Requester
    property: requester
    description: Should this request be made as the installation or as the user?
    default: '`installation`'
    type: string
examples:
  - type: octokit
    method: issues.create
    title: A new issue
  - type: octokit
    method: pullRequests.merge
    number: 2
  - type: octokit
    method: migrations.getImportStatus
    requester: user
