title: Update branch protection
description: Updates the branch protection on a branch in the course repository
usage: "In addition to `branch`, this action accepts the same options as [`@octokit/rest`'s `updateBranchProtection](https://octokit.github.io/rest.js/#api-Repos-updateBranchProtection)."
options:
  - title: Branch
    property: branch
    description: The branch name to update branch protection
    default: '`master`'
    type: string
  - title: Enforce for Admins
    property: enforce_admins
    description: Enforce all configured restrictions for administrators.
    default: true
    type: boolean
examples:
  - type: updateBranchProtection
  - type: updateBranchProtection
    branch: my-protected-branch
  - type: updateBranchProtection
    enforce_admins: false
