title: Create a new file
description: Creates a new file
options:
  - title: File name
    property: filename
    required: true
    description: Name of the file in your course repository's response directory.
    type: string
  - title: Branch
    property: branch
    default: master
    description: The branch to create the new file on.
    type: string
  - title: Commit message
    property: message
    default: Creating new file {{ new_name || filename }}
    description: The commit message when adding the file
    type: string
  - title: Template data
    property: data
    description: Variables that you can pass to your file.
    type: object
  - title: New name
    property: new_name
    default: If `new_name` is not provided, the file will have the same name as it does in the course repository.
    description: What the new file should be called
    type: string
examples:
  - type: createFile
    filename: README.md
    data:
      bestUser: JasonEtco
  - type: createFile
    filename: response.md
  - type: createFile
    filename: response.md
    branch: my-feature-branch
  - type: createFile
    filename: example-codeowners.md
    new_name: .github/CODEOWNERS

