title: Create a PR Review
description: Creates a Pull Request review on GitHub
usage: Provide a title and a body to create a new issue on GitHub.
options:
  - title: Body
    property: body
    required: true
    description: Body of the new issue
    type: string
  - title: Event
    property: event
    required: true
    description: A pull request review event
    type: string
  - title: Pull Request number
    property: number
    required: false
    description: The number of a Pull Request
    default: Gets the number from the webhook payload
    type: number
  - title: Pull Request
    property: pullRequest
    required: false
    description: The title or number of a Pull Request
    type:
      - string
      - number
examples:
  - type: createReview
    body: "review-body.md"
    event: REQUEST_CHANGES
  - type: createReview
    body: "review-body.md"
    event: REQUEST_CHANGES
    number: 3