title: Create a label
description: Creates a new label on GitHub.
options:
  - title: Name
    property: name
    required: true
    description: Name of the label.
    type: string
  - title: Color
    property: color
    required: true
    description: The hexadecimal color code for the label, without the leading `#`.
    type: string
  - title: Description
    property: description
    required: false
    description: A short description of the label.
    type: string
examples:
  - type: createLabel
    name: a label
    color: f87000
  - type: createLabel
    name: another label
    color: f87000
    description: This label is used to label things