title: Open a Pull Request
description: Opens a new Pull Request on GitHub.
usage: Provide a title and a body to create a new issue on GitHub.
options:
  - title: Title
    property: title
    required: true
    description: Title of the new Pull Request
    type: string
  - title: Body
    property: body
    required: true
    description: Body of the new Pull Request
    type: string
  - title: Head
    property: head
    required: true
    description: Head of the Pull Request (which branch to merge from)
  - title: Base
    property: base
    default: master
    description: Base of the Pull Request (which branch to merge into)
    type: string
  - title: Comments
    property: comments
    required: false
    description: A list of comments to add to the newly generated issue
    type: string[]
examples:
  - type: createPullRequest
    title: "Title of the Pull Request"
    body: "pull-request-body.md"
    comments:
      - "pr-comment.md"