title: Merge a Pull Request
description: Merges a Pull Request on GitHub.
options:
  - title: Pull Request
    property: pullRequest
    default: Gets the Pull Request number from the webhook payload
    description: Title or Number of the new Pull Request
    type:
      - string
      - number
examples:
  - type: mergePullRequest
  - type: mergePullRequest
    pullRequest: 1
  - type: mergePullRequest
    pullRequest: "An existing pull request"