title: Create a Status
description: Creates a status on a commit or pull request
usage: Provide a title and a body to create a new issue on GitHub.
options:
  - title: State
    property: state
    description: If the state is a string and a valid state, the status' state will be that string. If its an object, it will be considered a [`gate`](../gate) action and evaluate to either `success` or `failure`
    required: true
    type:
      - string
      - object
  - title: State conditional, left side
    property: state.left
    description: A [`gate`](../gate) action. 
    type: string
  - title: State conditional, operator
    property: state.operator
    description: Response file name
    type: string
  - title: State conditional, right side
    property: state.right
    description: Response file name
    type: string
  - title: Description shown for a pending status
    property: pending.description
    description: Description for pending status
    type: string
  - title: URL for a pending status
    property: pending.target_url
    description: URL for pending status
    type: string
  - title: Description shown for a failing status
    property: failure.description
    description: Description for failure status
    type: string
  - title: URL for a failing status
    property: failure.target_url
    description: URL for failure status
    type: string
  - title: Description shown for a success status
    property: success.description
    description: Description for success status
    type: string
  - title: URL for a success status
    property: success.target_url
    description: URL for success status
    type: string
  - title: Commit sha
    property: sha
    description: Sha of the commit to set a status on
    default: Gets sha from webhook payload
    type: string
  - title: Status context
    property: context
    description: Status identifier string
    default: The `slug` of the step
    type: string
examples:
  - type: createStatus
    state: "%pull_request.body%"
    failure:
      description: Your pull request needs a description in the body. Please edit the pull request to include a body.
      target_url: https://help.github.com/articles/editing-a-comment/
    success:
      description: Your pull request has a body description.
      target_url: https://help.github.com/articles/creating-a-pull-request/#creating-the-pull-request
  - type: createStatus
    state: "failure"
    context: my-special-context