title: Respond to an issue or PR
description: Posts a comment on an issue or pull request
options:
  - title: Response body
    property: with
    description: A markdown filename to use as the comment body
    type: string
    required: true
  - title: Issue number or title
    property: issue
    description: The number or title of an issue/pull request
    default: Gets the issue number from the webhook payload
    type:
      - string
      - number
examples:
  - type: respond
    with: "my-response.md"

  - type: respond
    with: "my-response.md"
    issue: "Title of an issue to comment in"

  - type: respond
    with: "my-response.md"
    issue: 4