title: Create Project Board
description: Creates a new Project Board in the user's repository
options:
  - title: Name
    property: name
    required: true
    description: Name of the new project board
    type: string
  - title: Description
    property: body
    description: The description of the new project board
    type: string
  - title: Columns
    property: columns
    description: A list of column names to create
    type: string[]
examples:
  - type: createProjectBoard
    name: New board
  - type: createProjectBoard
    name: New board
    description: This board is the best board
    columns:
      - To do
      - In progress
      - Done
