title: Create a PR comment
description: Creates a comment on a pull request on GitHub
options:
  - title: Body
    property: body
    required: true
    description: Body of the new comment
    type: string
  - title: File
    property: file
    required: true
    description: The file to comment on
    type: string
  - title: Pull Request
    property: pullRequest
    required: false
    description: The title or number of a Pull Request
    type:
      - string
      - number
  - title: Line number
    property: position
    required: true
    description: The line number to comment on. This is the line number in the PR's unified diff.
    type: number
examples:
  - type: createPullRequestComment
    body: suggested-changes.md
    file: some-file.js
    position: 5
  - type: createPullRequestComment
    pullRequest: 10
    body: suggested-changes.md
    file: some-file.js
    position: 5
  - type: createPullRequestComment
    pullRequest: Some pull request
    body: suggested-changes.md
    file: some-file.js
    position: 5
