title: Create an issue
description: Creates a new issue on GitHub.
usage: Provide a title and a body to create a new issue on GitHub.
options:
  - title: Title
    property: title
    required: true
    description: Title of the new issue
    type: string
  - title: Body
    property: body
    required: true
    description: Body of the new issue
    type: string
  - title: Comments
    property: comments
    required: false
    description: A list of comments to add to the newly generated issue
    type: string[]
examples:
  - type: createIssue
    title: "Title of the issue"
    body: "issue-body.md"
    comments:
      - "issue-comment.md"