title: HTML Contains Tag
description: Checks if the provided HTML string contains a specific HTML tag
options:
  - title: HTML
    property: html
    description: The HTML string to check for a tag
    type: string
    required: true
  - title: Tag
    property: tag
    description: The HTML tag, like `a` or `div`.
    type: string
    required: true
  - title: Attribute
    property: attribute
    description: An attribute that the tag must have
    type: string
examples:
  - type: htmlContainsTag
    html: '<html><div>Hello!</div></html>'
    tag: div
  - type: htmlContainsTag
    html: '<html><img src="example.png" /></html>'
    tag: img
    attribute: src
