title: Delete a branch
description: Deletes the provided branch
usage: Usually after a pull request is merged, provide the name of the branch to delete it.
options:
  - title: Branch
    property: branch
    description: The name of the branch to delete
    required: true
    type: string
examples:
  - type: deleteBranch
    branch: example-branch
