title: Get a tree
description: Gets a Git tree at either a given sha or the head of master
options:
  - title: Sha
    property: sha
    default: The sha of the head commit of the default branch (usually master)
    description: The sha to get the tree
    type: string
  - title: Recursive
    property: recursive
    default: false
    description: Get a recursive tree
    type: boolean
examples:
  - type: getTree
  - type: getTree
    recursive: true
